version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.24
    env_file: .env
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: 4466
        databases:
          $POSTGRES_DB:
            connector: postgres
            host: postgres
            port: 5432
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true
  postgres:
    image: postgres:9.5
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
